#baseURL = "https://urinieto.netlify.app"
baseURL = "https://www.urinieto.com/"
#url = "https://urinieto.netlify.app"
#url = "https://urinieto.com"
languageCode = "en-us"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

DefaultContentLanguage = "en"
sectionPagesMenu = "main"
Paginate = 8 # Number of posts to show in the home page
googleAnalytics = ""

[params]
title = "Oriol (Uri) Nieto"
author = "Oriol Nieto"
description = "Audio Researcher. Musician. Titan."
profilePicture = "wp-content/uploads/2023/uri-side.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/uri.css", "css/publications.css"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/urinieto/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/urinieto/"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/urinieto/"

[[params.socialIcons]]
icon = "fa-brands fa-bluesky"
title = "BlueSky"
url = "https://bsky.app/profile/urinieto.bsky.social"

# [[params.socialIcons]]
# icon = "fa-twitter"
# title = "X"
# url = "https://www.x.com/urinieto/"

[[params.socialIcons]]
icon = "fa-youtube"
title = "youtube"
url = "https://www.youtube.com/channel/UC_8n33wIclFtmwORvURYYHA"

[[params.socialIcons]]
icon = "fa-soundcloud"
title = "soundcloud"
url = "https://soundcloud.com/urinieto"

[[params.socialIcons]]
icon = "fa-graduation-cap"
title = "google-scholar"
url = "https://scholar.google.com/citations?user=7CyUUcMAAAAJ&hl=en"

[menu]
    [[menu.main]]
      name = "Posts"
      weight = 100
      identifier = "posts"
      title = "Home"
      url = "/"

    [[menu.main]]
      name = "Publications"
      weight = 200
      identifier = "publications"
      url = "/publications/"

    [[menu.main]]
      name = "Music Videos"
      weight = 300
      identifier = "music-videos"
      url = "/music-videos/"

    [[menu.main]]
        identifier = "cv"
        name = "CV"
        title = "CV section"
        url = "/cv/"
        weight = 400

    [[menu.main]]
        identifier = "about"
        name = "About Me"
        title = "About section"
        url = "/about/"
        weight = 500

    [[menu.main]]
      name = "Archive"
      weight = 600
      identifier = "archive"
      url = "/posts/"

